/// Generate Bash shell completions for tmx
pub fn generate_completions() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# Generated by tmx v{}
# Bash shell completions for tmx

_tmx_completions() {{
    local cur prev words cword

    # Use _init_completion if available (from bash-completion package)
    # Otherwise fall back to manual initialization
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        # Fallback for environments without bash-completion
        COMPREPLY=()
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
        cword=$COMP_CWORD
        words=("${{COMP_WORDS[@]}}")
    fi

    # Get the subcommand (first argument after tmx)
    local cmd=""
    if [[ $cword -gt 1 ]]; then
        cmd="${{words[1]}}"
    fi

    case "$cmd" in
        "")
            # No subcommand yet - suggest subcommands
            local commands="open close refresh list init validate completions help o c r ls"
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
            return 0
            ;;
        open|o)
            # Suggest running sessions first, then configured-not-running
            if [[ $cword -eq 2 ]]; then
                local running=$(tmx __list-running 2>/dev/null)
                local configured=$(tmx __list-configured 2>/dev/null)
                # Combine: running first, then configured that aren't running
                local sessions="$running"
                for s in $configured; do
                    if ! echo "$running" | grep -qx "$s"; then
                        sessions="$sessions $s"
                    fi
                done
                COMPREPLY=($(compgen -W "$sessions" -- "$cur"))
            fi
            return 0
            ;;
        close|c)
            # Suggest running sessions
            if [[ $cword -eq 2 ]]; then
                local sessions=$(tmx __list-running 2>/dev/null)
                COMPREPLY=($(compgen -W "$sessions" -- "$cur"))
            fi
            return 0
            ;;
        refresh|r)
            # Suggest running sessions
            if [[ $cword -eq 2 ]]; then
                local sessions=$(tmx __list-running 2>/dev/null)
                COMPREPLY=($(compgen -W "$sessions" -- "$cur"))
            fi
            return 0
            ;;
        completions)
            # Suggest shell types
            if [[ $cword -eq 2 ]]; then
                local shells="fish bash zsh"
                COMPREPLY=($(compgen -W "$shells" -- "$cur"))
            fi
            return 0
            ;;
        list|ls|init|validate|help)
            # No additional completions needed
            return 0
            ;;
        *)
            return 0
            ;;
    esac
}}

complete -F _tmx_completions tmx
"#,
        version
    )
}
