/// Generate Fish shell completions for tmx
pub fn generate_completions() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# Generated by tmx v{}
# Fish shell completions for tmx

complete -c tmx -f

# Subcommands
complete -c tmx -n "__fish_use_subcommand" -a "start" -d "Start/attach to session"
complete -c tmx -n "__fish_use_subcommand" -a "stop" -d "Stop session"
complete -c tmx -n "__fish_use_subcommand" -a "list" -d "List configured and running sessions"
complete -c tmx -n "__fish_use_subcommand" -a "running" -d "Show running tmux sessions"
complete -c tmx -n "__fish_use_subcommand" -a "init" -d "Initialize config file"
complete -c tmx -n "__fish_use_subcommand" -a "validate" -d "Validate config syntax"
complete -c tmx -n "__fish_use_subcommand" -a "completions" -d "Generate shell completions"
complete -c tmx -n "__fish_use_subcommand" -a "alias" -d "Generate shell alias"
complete -c tmx -n "__fish_use_subcommand" -a "setup" -d "Setup shell integration"
complete -c tmx -n "__fish_use_subcommand" -a "help" -d "Show help message"

# Helper functions
function __tmx_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and test $cmd[2] = $argv[1]
end

function __tmx_configured_sessions
    tmx __list-configured 2>/dev/null
end

function __tmx_running_sessions
    tmx __list-running 2>/dev/null
end

# Dynamic completions for start (configured sessions)
complete -c tmx -n "__tmx_using_command start" -a "(__tmx_configured_sessions)" -d "Session"

# Dynamic completions for stop (running sessions)
complete -c tmx -n "__tmx_using_command stop" -a "(__tmx_running_sessions)" -d "Running"

# Shell options for completions command
complete -c tmx -n "__tmx_using_command completions" -a "fish" -d "Fish shell"

# Shell options for alias command
complete -c tmx -n "__tmx_using_command alias" -a "fish" -d "Fish shell"

# Shell options for setup command
complete -c tmx -n "__tmx_using_command setup" -a "fish" -d "Fish shell"

# Help options
complete -c tmx -s h -l help -d "Show help message"
"#,
        version
    )
}

/// Generate Fish shell alias for t -> tmx
pub fn generate_alias() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# Generated by tmx v{}
# Single-letter alias for tmx

function t -d "Alias for tmx - Tmux session manager"
    tmx $argv
end
"#,
        version
    )
}

/// Generate setup instructions for Fish shell
pub fn generate_setup_instructions() -> &'static str {
    r#"# TMX Fish Shell Setup

To complete the setup, run the following commands:

## 1. Install tmx completions
tmx completions fish > ~/.config/fish/completions/tmx.fish

## 2. Install t alias completions
tmx completions fish | sed 's/tmx/t/g; s/__tmx/__t/g' > ~/.config/fish/completions/t.fish

## 3. Install t alias function
tmx alias fish > ~/.config/fish/functions/t.fish

## 4. Reload Fish shell
source ~/.config/fish/config.fish

After setup, you can use both 'tmx' and 't' commands with full tab completion!
"#
}
