/// Generate Fish shell completions for tmx
pub fn generate_completions() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# Generated by tmx v{}
# Fish shell completions for tmx

complete -c tmx -f

# Subcommands
complete -c tmx -n "__fish_use_subcommand" -a "start" -d "Start/attach to session"
complete -c tmx -n "__fish_use_subcommand" -a "stop" -d "Stop session"
complete -c tmx -n "__fish_use_subcommand" -a "list" -d "List configured and running sessions"
complete -c tmx -n "__fish_use_subcommand" -a "init" -d "Initialize config file"
complete -c tmx -n "__fish_use_subcommand" -a "validate" -d "Validate config syntax"
complete -c tmx -n "__fish_use_subcommand" -a "completions" -d "Generate shell completions"
complete -c tmx -n "__fish_use_subcommand" -a "help" -d "Show help message"

# Helper functions
function __tmx_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and test $cmd[2] = $argv[1]
end

function __tmx_configured_sessions
    tmx __list-configured 2>/dev/null
end

function __tmx_running_sessions
    tmx __list-running 2>/dev/null
end

# Dynamic completions for start (configured sessions)
complete -c tmx -n "__tmx_using_command start" -a "(__tmx_configured_sessions)" -d "Session"

# Dynamic completions for stop (running sessions)
complete -c tmx -n "__tmx_using_command stop" -a "(__tmx_running_sessions)" -d "Running"

# Shell options for completions command
complete -c tmx -n "__tmx_using_command completions" -a "fish" -d "Fish shell"

# Help options
complete -c tmx -s h -l help -d "Show help message"
"#,
        version
    )
}
