/// Generate Fish shell completions for tmx
pub fn generate_completions() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# Generated by tmx v{}
# Fish shell completions for tmx

complete -c tmx -f

# Subcommands
complete -c tmx -n "__fish_use_subcommand" -a "open" -d "Open/attach to session"
complete -c tmx -n "__fish_use_subcommand" -a "close" -d "Close session"
complete -c tmx -n "__fish_use_subcommand" -a "refresh" -d "Refresh session layout"
complete -c tmx -n "__fish_use_subcommand" -a "list" -d "List configured and running sessions"
complete -c tmx -n "__fish_use_subcommand" -a "init" -d "Initialize config file"
complete -c tmx -n "__fish_use_subcommand" -a "validate" -d "Validate config syntax"
complete -c tmx -n "__fish_use_subcommand" -a "completions" -d "Generate shell completions"
complete -c tmx -n "__fish_use_subcommand" -a "help" -d "Show help message"

# Command aliases
complete -c tmx -n "__fish_use_subcommand" -a "o" -d "Alias for open"
complete -c tmx -n "__fish_use_subcommand" -a "c" -d "Alias for close"
complete -c tmx -n "__fish_use_subcommand" -a "r" -d "Alias for refresh"
complete -c tmx -n "__fish_use_subcommand" -a "ls" -d "Alias for list"

# Helper functions
function __tmx_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and test $cmd[2] = $argv[1]
end

function __tmx_configured_sessions
    tmx __list-configured 2>/dev/null
end

function __tmx_running_sessions
    tmx __list-running 2>/dev/null
end

function __tmx_all_sessions
    # Combine configured and running sessions, removing duplicates
    begin
        tmx __list-configured 2>/dev/null
        tmx __list-running 2>/dev/null
    end | sort -u
end

# Dynamic completions for open (configured + running sessions)
complete -c tmx -n "__tmx_using_command open" -a "(__tmx_all_sessions)" -d "Session"
complete -c tmx -n "__tmx_using_command o" -a "(__tmx_all_sessions)" -d "Session"

# Dynamic completions for close (running sessions)
complete -c tmx -n "__tmx_using_command close" -a "(__tmx_running_sessions)" -d "Running"
complete -c tmx -n "__tmx_using_command c" -a "(__tmx_running_sessions)" -d "Running"

# Dynamic completions for refresh (running sessions)
complete -c tmx -n "__tmx_using_command refresh" -a "(__tmx_running_sessions)" -d "Running"
complete -c tmx -n "__tmx_using_command r" -a "(__tmx_running_sessions)" -d "Running"

# Shell options for completions command
complete -c tmx -n "__tmx_using_command completions" -a "fish" -d "Fish shell"
complete -c tmx -n "__tmx_using_command completions" -a "bash" -d "Bash shell"
complete -c tmx -n "__tmx_using_command completions" -a "zsh" -d "Zsh shell"

# Help options
complete -c tmx -s h -l help -d "Show help message"
"#,
        version
    )
}
