/// Generate Zsh shell completions for tmx
pub fn generate_completions() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"#compdef tmx
# Generated by tmx v{}
# Zsh shell completions for tmx

# Helper function to get configured sessions
_tmx_configured_sessions() {{
    local -a sessions
    sessions=(${{(f)"$(tmx __list-configured 2>/dev/null)"}})
    if (( ${{#sessions}} > 0 )); then
        _describe 'configured session' sessions
    fi
}}

# Helper function to get running sessions
_tmx_running_sessions() {{
    local -a sessions
    sessions=(${{(f)"$(tmx __list-running 2>/dev/null)"}})
    if (( ${{#sessions}} > 0 )); then
        _describe 'running session' sessions
    fi
}}

# Helper function to get all sessions (configured + running, deduplicated)
_tmx_all_sessions() {{
    local -a sessions
    sessions=(${{(f)"$( (tmx __list-configured 2>/dev/null; tmx __list-running 2>/dev/null) | sort -u )"}})
    if (( ${{#sessions}} > 0 )); then
        _describe 'session' sessions
    fi
}}

# Helper function to get available shells
_tmx_shells() {{
    local -a shells
    shells=(
        'fish:Fish shell completions'
        'bash:Bash shell completions'
        'zsh:Zsh shell completions'
    )
    _describe 'shell' shells
}}

# Main completion function
_tmx() {{
    local line state

    _arguments -C \
        '(-h --help)'{{-h,--help}}'[Show help message]' \
        '(-c --config)'{{-c,--config}}'[Path to config file]:config file:_files' \
        '(-v --verbose)'{{-v,--verbose}}'[Enable verbose/debug output]' \
        '1: :_tmx_commands' \
        '*::arg:->args'

    case $line[1] in
        open|o)
            _tmx_all_sessions
            ;;
        close|c)
            _tmx_running_sessions
            ;;
        refresh|r)
            _tmx_running_sessions
            ;;
        completions)
            _tmx_shells
            ;;
    esac
}}

# Subcommand definitions
_tmx_commands() {{
    local -a commands
    commands=(
        'open:Open or attach to a session'
        'o:Alias for open'
        'close:Close a running session'
        'c:Alias for close'
        'refresh:Refresh the layout of a running session'
        'r:Alias for refresh'
        'list:List configured and running sessions'
        'ls:Alias for list'
        'init:Initialize configuration file'
        'validate:Validate configuration syntax'
        'completions:Generate shell completions'
        'help:Show help message'
    )
    _describe 'command' commands
}}

_tmx "$@"
"#,
        version
    )
}
